# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: index-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: index-app
  template:
    metadata:
      labels:
        app: index-app
    spec:
      containers:
      - name: index-container
        image: 225989348530.dkr.ecr.us-east-2.amazonaws.com/app/vinapp:latest
        ports:
        - containerPort: 80
